# 注册到eureka服务端的微服务名称
spring:
  application:
    name: eureka-consumer-feign-hystrix
# 服务提供端口
server:
  port: 8008
# 注册到eureka服务端的地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
  # 显示指定微服务的名称，默认ip:应用名称:端口(192.168.1.7:eureka-consumer-feign-hystrix:8008)
  instance:
    instance-id: eureka-consumer-feign-hystrix-8008
    prefer-ip-address: true
# 开启feign支持hystrix，默认关闭
feign:
  hystrix:
    enabled: true