spring:
  application:
    name: redis-util
  redis:
    host: 127.0.0.1
    port: 6379
    password: redis_password
    jedis:
      pool:
        min-idle: 4
        max-wait: 1000
        max-idle: 1000
        max-active: 9